set -g mouse on
set-option -g set-clipboard on
set -g default-terminal "tmux-256color"
set -g escape-time 0
set -g status-interval 3
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

# Prefix key: change from default C-b to C-s
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Reload config with Prefix + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Split panes in current working directory
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# New window in current working directory
bind c new-window -c "#{pane_current_path}"

# Maximize/restore pane with m
bind -r m resize-pane -Z

# Vi mode for copy mode
set-window-option -g mode-keys vi

# Easier pane navigation with vim keys
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
# set -g status-left ""

set -g @tpm_plugins ' \
   tmux-plugins/tpm   \
   dracula/tmux       \
'

set -g @dracula-plugins "battery network time"

set -g @dracula-show-powerline true
set -g @dracula-show-left-icon "#h"
set -g @dracula-transparent-powerline-bg true
set -g @dracula-military-time true
set -g @dracula-time-format "%a %d/%m/%Y %R"
set -g @dracula-battery-label false
set -g @dracula-show-battery-status true

set -g @dracula-network-ethernet-label "󰒪 Ethernet"
set -g @dracula-network-offline-label "󱍢 "
set -g @dracula-network-wifi-label " "

set -g @dracula-battery-colors "yellow dark_gray"

set -g status-position top

run '~/.tmux/plugins/tpm/tpm'
