set -g default-terminal "screen-256color"

set -g set-clipboard on    # Use system clipboard
set -g mouse on            # Enable mouse support
set -g escape-time 0       # Remove delay for exiting insert mode with ESC in Neovim
set -g status-interval 3   # Update the status bar every 3 seconds (default: 15 seconds)

# Set prefix key
unbind C-b              # Unbind the default prefix key
set -g prefix C-Space   # Set new prefix key to Ctrl+Space

# Refresh tmux config with r
unbind r
bind r source-file ~/.config/tmux/tmux.conf

unbind %
bind \\ split-window -h -c "#{pane_current_path}" # Split horizontally in CWD with \

unbind \"
bind - split-window -v -c "#{pane_current_path}" # Split vertically in CWD with -

bind c new-window -c "#{pane_current_path}"

# Use vim arrow keys to resize
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Use m key to maximize pane
bind -r m resize-pane -Z

# Enable vi mode to allow us to use vim keys to move around in copy mode (Prefix + [ places us in copy mode)
set-window-option -g mode-keys vi

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on # Automatically renumber windows when one is closed

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'christoomey/vim-tmux-navigator' # Enable navigating between nvim and tmux
set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux sessions after computer restart

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
